Solution2
javastartbootcamp/bootcamp-project-seleniumfan pull request #21
Opened 2023-10-02 21:03 UTC by seleniumfan

2023-10-03 18:26 UTC, marcinkunert requested changes
Wygląda w porządku, ale znalazł się tutaj commit, którego tutaj być nie powinno (dotyczący wysyłki maili).
W takim razie możesz spróbować wycofać ten commit poprzez stworzenie jego lustrzanego odbicia (revert), albo cofnąć się do momentu, gdzie żadnego z tych commitów jeszcze nie było, np. przez reset --soft i stworzenie commita tylko z oczekiwanymi zmianami. W każdym razie tak  jak jest teraz nie może zostać.

2023-10-03 18:26 UTC, marcinkunert commented on src/main/resources/application.properties
to zmiany dotyczące innego pull requesta, nie powinny się znaleźć w tym

2023-10-03 18:47 UTC, seleniumfan commented on src/main/resources/application.properties
@marcinkunert : Ok wykonałem revert

2023-10-04 19:33 UTC, marcinkunert approved these changes

2023-10-07 20:02 UTC, merged