#9 Poprawa linkow do youtube
javastartbootcamp/bootcamp-project-seleniumfan pull request #29
Opened 2023-10-06 23:37 UTC by seleniumfan

2023-10-07 20:05 UTC, marcinkunert requested changes
Tutaj też znalazły się zmiany dotyczące 2 zadań. Wycofaj te niepotrzebne.

2023-10-07 22:43 UTC, seleniumfan commented
Zrobione

2023-10-12 07:29 UTC, slawekludwiczak requested changes
W panelu admina w kilku miejscach wyświetlany jest tekst `Linki do filmów - tylko identyfikatory filmów z youtube` - przydałoby się go dostosować do nowych możliwości

2023-10-12 07:29 UTC, slawekludwiczak commented on src/main/java/pl/javastart/bootcamp/domain/admin/task/TaskService.java
> +    }
Powtarzasz ten sam kod w 4 miejscach, raczej prosi się wydzielenie tego do osobnej klasy i np. metody statycznej typu `YoutubeUrls.mapToEmbed(...)`

2023-10-12 07:29 UTC, slawekludwiczak commented on src/main/java/pl/javastart/bootcamp/domain/admin/template/TrainingTemplateService.java
> +    }
Powtarzasz ten sam kod w 4 miejscach, raczej prosi się wydzielenie tego do osobnej klasy i np. metody statycznej typu `YoutubeUrls.mapToEmbed(...)`

2023-10-12 07:29 UTC, slawekludwiczak commented on src/main/java/pl/javastart/bootcamp/domain/admin/topic/TopicService.java
> +    }
Powtarzasz ten sam kod w 4 miejscach, raczej prosi się wydzielenie tego do osobnej klasy i np. metody statycznej typu `YoutubeUrls.mapToEmbed(...)`

2023-10-12 07:29 UTC, slawekludwiczak commented on src/main/java/pl/javastart/bootcamp/domain/training/lesson/LessonService.java
> +    }
Powtarzasz ten sam kod w 4 miejscach, raczej prosi się wydzielenie tego do osobnej klasy i np. metody statycznej typu `YoutubeUrls.mapToEmbed(...)`

2023-10-13 06:46 UTC, merged