#7 Nie działa generowanie testowej umowy
javastartbootcamp/bootcamp-project-seleniumfan pull request #30
Opened 2023-10-07 17:57 UTC by seleniumfan

2023-10-07 20:08 UTC, marcinkunert requested changes

2023-10-07 20:08 UTC, marcinkunert commented on src/main/resources/application.properties
> +javastart.agreements-dir=src/main/resources/agreement
Przy takiej ścieżce wygenerowana umowa od razu "chce" być indeksowana przez gita. Zmień docelowy folder na coś bardziej pasującego i dodaj ten folder od `.gitignore`, albo użyj takiego, który jest już ignorowany.

2023-10-07 22:44 UTC, seleniumfan commented
Done

2023-10-12 07:37 UTC, slawekludwiczak approved these changes

2023-10-12 07:37 UTC, merged